version: '3'
services:
  redmine:
    restart: always
    image: nixyslab/nxs-chat-redmine:3.4.6-2.0
    expose:
    - 3000
    volumes:
    - ./volumes/redmine/files:/usr/src/redmine/files
    - ./volumes/redmine/sqlite:/usr/src/redmine/sqlite
    - ./volumes/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    - ./volumes/redmine/config/additional_environment.rb:/usr/src/redmine/config/additional_environment.rb
    environment:
    - VIRTUAL_HOST=demo.nxs-chat.example.com
    - VIRTUAL_PORT=3000
    - VIRTUAL_PROTO=http
    - LETSENCRYPT_HOST=demo.nxs-chat.example.com
    - LETSENCRYPT_EMAIL=ssl@example.com
#    - REDMINE_NO_DB_MIGRATE=yes
    networks:
    - default
    - proxy

  nxs-chat-srv:
    restart: always
    image: nixyslab/nxs-chat-srv:0.3.1
    expose:
    - 80
    depends_on:
    - redmine
    - mysql
    - redis
    environment:
    - VIRTUAL_HOST=bot-api.demo.nxs-chat.example.com
    - VIRTUAL_PORT=80
    - VIRTUAL_PROTO=http
    - LETSENCRYPT_HOST=bot-api.demo.nxs-chat.example.com
    - LETSENCRYPT_EMAIL=ssl@example.com
    - NXS_CHAT_SRV_INITIALIZE=set_webhook,create_tables
    - LOGGING_LEVEL=31
    - BIND_PORT=80
    - BIND_SSL_USE_SSL='false'
    - TELEGRAM_BOT_API_KEY=
    - TELEGRAM_AUTH_TOKEN=
    - TELEGRAM_WEBHOOK_HOST='https://bot-api.demo.nxs-chat.example.com:443'
    - MYSQL_NAME=
    - MYSQL_USER=
    - MYSQL_PASS=
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - REDIS_KEYS_SPACE=demo
    - REDIS_CLUSTER='false'
    - REDIS_NODES=redis:6379
    - REDMINE_URL='https://demo.nxs-chat.example.com'
    - REDMINE_HOST='http://redmine:3000'
    - REDMINE_API_KEY=
    - REDMINE_AUTH_TOKEN=
    - REDMINE_PRESALE_API_KEY=
    - REDMINE_PRESALE_PROJECT_NAME=Pre-sale
    - REDMINE_ISSUE_LIST_QUERY_ID=
    - REDMINE_SSL_VERIFYHOST='false'
    - REDMINE_CF_TELEGRAM=
    - REDMINE_STATUS_IN_PROGRESS=
    - REDMINE_STATUS_RESOLVED=
    - REDMINE_STATUS_NEED_FEEDBACK=
    - STATISTIC_AUTH_TOKEN=
    - LABELS_DEFAULT_LANG=
    - LABELS_LABELS_PATH=
    - GREETINGS_LANG_1=en
    - GREETINGS_TEXT_1='%{userfname}, welcome to customer care system Demo chat!'
    - GREETINGS_LANG_2=ru
    - GREETINGS_TEXT_2='%{userfname}, добро пожаловать в Demo-версию чата поддержки клиентов!'
    networks:
    - default
    - proxy

  redis:
    restart: always
    image: redis:latest
    command:
    - redis-server
    - --save 30 1
    volumes:
    - ./volumes/redis/data:/data
    networks:
    - default

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=
    networks:
    - default

networks:
  default:
    driver: bridge
  proxy:
    external:
       name: nginxproxy_proxy
