apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: redmine
  namespace: demo-nxs-chat-srv
spec:
  secretName: redmine-tls
  issuerRef:
    name: letsencrypt
  commonName: demo.nxs-chat.example.com
  dnsNames:
  - demo.nxs-chat.example.com
  acme:
    config:
    - http01:
        ingress: redmine
      domains:
      - demo.nxs-chat.example.com

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nxs-chat-srv
  namespace: demo-nxs-chat-srv
spec:
  secretName: nxs-chat-srv-tls
  issuerRef:
    name: letsencrypt
  commonName: bot-api.demo.nxs-chat.example.com
  dnsNames:
  - bot-api.demo.nxs-chat.example.com
  acme:
    config:
    - http01:
        ingress: nxs-chat-srv
      domains:
      - bot-api.demo.nxs-chat.example.com
