apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine
  namespace: demo-nxs-chat-srv
data:
  configuration.yml: |
    default:
      delivery_method: :smtp
      smtp_settings:
        enable_starttls_auto: true
        address: 'mail.example.com'
        ssl: true
        port: 465
        domain: 'example.com'
        authentication: :plain
        user_name: ''
        password: ''
      attachments_storage_path:
      autologin_cookie_name:
      autologin_cookie_path:
      autologin_cookie_secure:
      scm_subversion_command:
      scm_mercurial_command:
      scm_git_command:
      scm_cvs_command:
      scm_bazaar_command:
      scm_darcs_command:
      scm_subversion_path_regexp:
      scm_mercurial_path_regexp:
      scm_git_path_regexp:
      scm_cvs_path_regexp:
      scm_bazaar_path_regexp:
      scm_darcs_path_regexp:
      scm_filesystem_path_regexp:
      scm_stderr_log_file:
      database_cipher_key:
      rmagick_font_path:
    production:
    development:
  additional_environment.rb: |
    config.logger = Logger.new(STDOUT)
    config.logger.level = Logger::WARN

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nxs-chat-srv
  namespace: demo-nxs-chat-srv
data:
  nxs-chat-srv.conf.j2: |-
    {
      "proc": {
        "pid_file": "/tmp/nxs-chat-srv.pid",
        "queue_worker_term_timeout": 10,
        "rest_api_term_timeout": 10,
        "daemonize": false
      },
      "logging": {
        "level": 31,
        "path": "/dev/stdout"
      },
      "bind": {
        "iface": "0.0.0.0",
        "port": 80,
        "ssl": {
          "use_ssl": false,
          "crt": "/etc/nxs-chat-srv/ssl/crt.pem",
          "key": "/etc/nxs-chat-srv/ssl/key.pem"
        }
      },
      "telegram": {
        "bot_api_addr": "https://api.telegram.org",
        "bot_api_key": "{{ telegram_bot_api_key }}",
        "auth_token": "{{ telegram_auth_token }}",
        "webhook_host": "https://bot-api.demo.nxs-chat.example.com:443",
        "proxy": {
          "type": "none",
          "host": "",
          "port": 0,
          "auth": {
            "type": "none",
            "user": "",
            "pass": ""
          }
        }
      },
      "mysql": {
        "name": "{{ mysql_name }}",
        "user": "{{ mysql_user }}",
        "pass": "{{ mysql_pass }}",
        "host": "{{ mysql_host }}",
        "port": {{ mysql_port }}
      },
      "redis": {
        "keys_space": "demo",
        "cluster": false,
        "nodes": [
          {
            "host": "redis.demo-nxs-chat-srv.svc",
            "port": 6379
          }
        ]
      },
      "redmine": {
        "url": "https://demo.nxs-chat.example.com",
        "host": "http://redmine.demo-nxs-chat-srv.svc:3000",
        "api_key": "{{ redmine_api_key }}",
        "auth_token": "{{ redmine_auth_token }}",
        "presale_api_key": "{{ redmine_presale_api_key }}",
        "presale_project_name": "Pre-sale",
        "issue_list_query_id": 0,
        "ssl_verifyhost": false,
        "cf_telegram": 0,
        "status_in_progress": 0,
        "status_need_feedback": 0,
        "status_resolved": 0
      },
      "ra_queue": {
        "pop_timeout_ms": 500,
        "queue_workers": 5
      },
      "cache": {
        "projects_ttl": 300,
        "users_ttl": 60,
        "issue_priorities_ttl": 300,
        "lock_file": "/tmp/nxs-chat-srv_cache.lock"
      },
      "dev_accounts": [
      ],
      "attachments": {
        "tlgrm_download_tmp_dir": "/var/spool/nxs-chat-srv/tlgrm",
        "rdmn_download_tmp_dir": "/var/spool/nxs-chat-srv/rdmn"
      },
      "statistic": {
        "auth_token": "{{ statistic_auth_token }}"
      },
      "labels": {
        "default_lang": "en",
        "labels_path": "/usr/share/nxs-chat-srv/labels/"
      },
      "greetings": [
        {
          "lang": "en",
          "text": "%{userfname}, welcome to customer care system Demo chat!"
        },
        {
          "lang": "ru",
          "text": "%{userfname}, добро пожаловать в Demo-версию чата поддержки клиентов!"
        }
      ]
    }
