apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redmine
  namespace: demo-nxs-chat-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: nixyslab/nxs-chat-redmine:3.4.6-2.0
        env:
#        - name: REDMINE_NO_DB_MIGRATE
#          value: 'yes'
        - name: REDMINE_DB_MYSQL
          valueFrom:
            secretKeyRef:
              name: redmine-config
              key: redmine_db_mysql
        - name: REDMINE_DB_PORT
          valueFrom:
            secretKeyRef:
              name: redmine-config
              key: redmine_db_port
        - name: REDMINE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: redmine-config
              key: redmine_db_username
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redmine-config
              key: redmine_db_password
        - name: REDMINE_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: redmine-config
              key: redmine_db_database
        - name: REDMINE_DB_ENCODING
          valueFrom:
            secretKeyRef:
              name: redmine-config
              key: redmine_db_encoding
        volumeMounts:
        - mountPath: /usr/src/redmine/config/configuration.yml
          name: redmine-config
          subPath: configuration.yml
        - mountPath: /usr/src/redmine/config/additional_environment.rb
          name: redmine-config
          subPath: additional_environment.rb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      volumes:
        - name: redmine-config
          configMap:
             name: redmine
             items:
              - key: configuration.yml
                path: configuration.yml
              - key: additional_environment.rb
                path: additional_environment.rb

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nxs-chat-srv
  namespace: demo-nxs-chat-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxs-chat-srv
  template:
    metadata:
      labels:
        app: nxs-chat-srv
    spec:
      containers:
      - name: nxs-chat-srv
        image: nixyslab/nxs-chat-srv:0.3.1
        env:
        - name: NXS_CHAT_SRV_INITIALIZE
          value: set_webhook,create_tables
        - name: LOGGING_LEVEL
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: logging_level
        - name: BIND_PORT
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: bind_port
        - name: BIND_SSL_USE_SSL
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: bind_ssl_use_ssl
        - name: TELEGRAM_BOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_bot_api_key
        - name: TELEGRAM_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_auth_token
        - name: TELEGRAM_WEBHOOK_HOST
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_webhook_host
        - name: TELEGRAM_PROXY_TYPE
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_proxy_type
        - name: TELEGRAM_PROXY_HOST
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_proxy_host
        - name: TELEGRAM_PROXY_PORT
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_proxy_port
        - name: TELEGRAM_PROXY_AUTH_TYPE
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_proxy_auth_type
        - name: TELEGRAM_PROXY_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_proxy_auth_user
        - name: TELEGRAM_PROXY_AUTH_PASS
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: telegram_proxy_auth_pass
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: mysql_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: mysql_user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: mysql_pass
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: mysql_host
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: mysql_port
        - name: REDIS_KEYS_SPACE
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redis_keys_space
        - name: REDIS_CLUSTER
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redis_cluster
        - name: REDIS_NODES
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redis_nodes
        - name: REDMINE_URL
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_url
        - name: REDMINE_HOST
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_host
        - name: REDMINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_api_key
        - name: REDMINE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_auth_token
        - name: REDMINE_PRESALE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_presale_api_key
        - name: REDMINE_PRESALE_PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_presale_project_name
        - name: REDMINE_ISSUE_LIST_QUERY_ID
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_issue_list_query_id
        - name: REDMINE_SSL_VERIFYHOST
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_ssl_verifyhost
        - name: REDMINE_CF_TELEGRAM
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_cf_telegram
        - name: REDMINE_STATUS_IN_PROGRESS
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_status_in_progress
        - name: REDMINE_STATUS_RESOLVED
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_status_resolved
        - name: REDMINE_STATUS_NEED_FEEDBACK
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: redmine_status_need_feedback
        - name: STATISTIC_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: statistic_auth_token
        - name: LABELS_DEFAULT_LANG
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: labels_default_lang
        - name: LABELS_LABELS_PATH
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: labels_labels_path
        - name: GREETINGS_LANG_1
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: greetings_lang_1
        - name: GREETINGS_TEXT_1
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: greetings_text_1
        - name: GREETINGS_LANG_2
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: greetings_lang_2
        - name: GREETINGS_TEXT_2
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-config
              key: greetings_text_2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  namespace: demo-nxs-chat-srv
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
