apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redmine
  namespace: demo-nxs-chat-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: nixyslab/nxs-chat-redmine:3.4.6-2.0
        env:
#        - name: REDMINE_NO_DB_MIGRATE
#          value: 'yes'
        - name: REDMINE_DB_MYSQL
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: redmine_db_mysql
        - name: REDMINE_DB_PORT
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: redmine_db_port
        - name: REDMINE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: redmine_db_username
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: redmine_db_password
        - name: REDMINE_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: redmine_db_database
        - name: REDMINE_DB_ENCODING
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: redmine_db_encoding
        volumeMounts:
        - mountPath: /usr/src/redmine/config/configuration.yml
          name: redmine-config
          subPath: configuration.yml
        - mountPath: /usr/src/redmine/config/additional_environment.rb
          name: redmine-config
          subPath: additional_environment.rb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      volumes:
        - name: redmine-config
          configMap:
             name: redmine
             items:
              - key: configuration.yml
                path: configuration.yml
              - key: additional_environment.rb
                path: additional_environment.rb

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nxs-chat-srv
  namespace: demo-nxs-chat-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxs-chat-srv
  template:
    metadata:
      labels:
        app: nxs-chat-srv
    spec:
      serviceAccountName: gitlab-deployer
      containers:
      - name: nxs-chat-srv
        image: nixyslab/nxs-chat-srv:0.3.1
        env:
        - name: NXS_CHAT_SRV_INITIALIZE
          value: set_webhook,create_tables
        - name: TELEGRAM_BOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: telegram_bot_api_key
        - name: TELEGRAM_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: telegram_auth_token
        - name: TELEGRAM_PROXY_AUTH_USER 
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: telegram_proxy_auth_user
        - name: TELEGRAM_PROXY_AUTH_PASS
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: telegram_proxy_auth_pass
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: mysql_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: mysql_user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: mysql_pass
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: mysql_host
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: mysql_port
        - name: REDMINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: redmine_api_key
        - name: REDMINE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: redmine_auth_token
        - name: REDMINE_PRESALE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: redmine_presale_api_key
        - name: STATISTIC_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nxs-chat-srv-secret
              key: statistic_auth_token
        volumeMounts:
        - mountPath: /usr/share/nxs-chat-srv/nxs-chat-srv.conf.j2
          name: nxs-chat-srv-config
          subPath: nxs-chat-srv.conf.j2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      volumes:
        - name: nxs-chat-srv-config
          configMap:
             name: nxs-chat-srv
             items:
              - key: nxs-chat-srv.conf.j2
                path: nxs-chat-srv.conf.j2

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  namespace: demo-nxs-chat-srv
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
