apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: demo-nxs-chat-srv
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ssl@example.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
